import type { Metadata } from 'next'
import { Readex_Pro } from 'next/font/google'
import './globals.css'
import CustomThemeProvider from '@/component/theme'
import ModalProvider from '@/view/modals'
import StoreProvider from './StoreProvider'

const readexPro = Readex_Pro({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={readexPro.className}>
        <StoreProvider>
          <CustomThemeProvider options={{ key: 'mui' }}>
            <ModalProvider />
            {children}
          </CustomThemeProvider>
        </StoreProvider>
      </body>
    </html>
  )
}
